require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ActasController do

  # This should return the minimal set of attributes required to create a valid
  # Acta. As you add validations to Acta, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "fecha_reunion" => "2013-11-11" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ActasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all actas as @actas" do
      acta = Acta.create! valid_attributes
      get :index, {}, valid_session
      assigns(:actas).should eq([acta])
    end
  end

  describe "GET show" do
    it "assigns the requested acta as @acta" do
      acta = Acta.create! valid_attributes
      get :show, {:id => acta.to_param}, valid_session
      assigns(:acta).should eq(acta)
    end
  end

  describe "GET new" do
    it "assigns a new acta as @acta" do
      get :new, {}, valid_session
      assigns(:acta).should be_a_new(Acta)
    end
  end

  describe "GET edit" do
    it "assigns the requested acta as @acta" do
      acta = Acta.create! valid_attributes
      get :edit, {:id => acta.to_param}, valid_session
      assigns(:acta).should eq(acta)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Acta" do
        expect {
          post :create, {:acta => valid_attributes}, valid_session
        }.to change(Acta, :count).by(1)
      end

      it "assigns a newly created acta as @acta" do
        post :create, {:acta => valid_attributes}, valid_session
        assigns(:acta).should be_a(Acta)
        assigns(:acta).should be_persisted
      end

      it "redirects to the created acta" do
        post :create, {:acta => valid_attributes}, valid_session
        response.should redirect_to(Acta.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved acta as @acta" do
        # Trigger the behavior that occurs when invalid params are submitted
        Acta.any_instance.stub(:save).and_return(false)
        post :create, {:acta => { "fecha_reunion" => "invalid value" }}, valid_session
        assigns(:acta).should be_a_new(Acta)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Acta.any_instance.stub(:save).and_return(false)
        post :create, {:acta => { "fecha_reunion" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested acta" do
        acta = Acta.create! valid_attributes
        # Assuming there are no other actas in the database, this
        # specifies that the Acta created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Acta.any_instance.should_receive(:update).with({ "fecha_reunion" => "2013-11-11" })
        put :update, {:id => acta.to_param, :acta => { "fecha_reunion" => "2013-11-11" }}, valid_session
      end

      it "assigns the requested acta as @acta" do
        acta = Acta.create! valid_attributes
        put :update, {:id => acta.to_param, :acta => valid_attributes}, valid_session
        assigns(:acta).should eq(acta)
      end

      it "redirects to the acta" do
        acta = Acta.create! valid_attributes
        put :update, {:id => acta.to_param, :acta => valid_attributes}, valid_session
        response.should redirect_to(acta)
      end
    end

    describe "with invalid params" do
      it "assigns the acta as @acta" do
        acta = Acta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Acta.any_instance.stub(:save).and_return(false)
        put :update, {:id => acta.to_param, :acta => { "fecha_reunion" => "invalid value" }}, valid_session
        assigns(:acta).should eq(acta)
      end

      it "re-renders the 'edit' template" do
        acta = Acta.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Acta.any_instance.stub(:save).and_return(false)
        put :update, {:id => acta.to_param, :acta => { "fecha_reunion" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested acta" do
      acta = Acta.create! valid_attributes
      expect {
        delete :destroy, {:id => acta.to_param}, valid_session
      }.to change(Acta, :count).by(-1)
    end

    it "redirects to the actas list" do
      acta = Acta.create! valid_attributes
      delete :destroy, {:id => acta.to_param}, valid_session
      response.should redirect_to(actas_url)
    end
  end

end
