require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProyectosUsersController do

  # This should return the minimal set of attributes required to create a valid
  # ProyectosUser. As you add validations to ProyectosUser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProyectosUsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all proyectos_users as @proyectos_users" do
      proyectos_user = ProyectosUser.create! valid_attributes
      get :index, {}, valid_session
      assigns(:proyectos_users).should eq([proyectos_user])
    end
  end

  describe "GET show" do
    it "assigns the requested proyectos_user as @proyectos_user" do
      proyectos_user = ProyectosUser.create! valid_attributes
      get :show, {:id => proyectos_user.to_param}, valid_session
      assigns(:proyectos_user).should eq(proyectos_user)
    end
  end

  describe "GET new" do
    it "assigns a new proyectos_user as @proyectos_user" do
      get :new, {}, valid_session
      assigns(:proyectos_user).should be_a_new(ProyectosUser)
    end
  end

  describe "GET edit" do
    it "assigns the requested proyectos_user as @proyectos_user" do
      proyectos_user = ProyectosUser.create! valid_attributes
      get :edit, {:id => proyectos_user.to_param}, valid_session
      assigns(:proyectos_user).should eq(proyectos_user)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProyectosUser" do
        expect {
          post :create, {:proyectos_user => valid_attributes}, valid_session
        }.to change(ProyectosUser, :count).by(1)
      end

      it "assigns a newly created proyectos_user as @proyectos_user" do
        post :create, {:proyectos_user => valid_attributes}, valid_session
        assigns(:proyectos_user).should be_a(ProyectosUser)
        assigns(:proyectos_user).should be_persisted
      end

      it "redirects to the created proyectos_user" do
        post :create, {:proyectos_user => valid_attributes}, valid_session
        response.should redirect_to(ProyectosUser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved proyectos_user as @proyectos_user" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectosUser.any_instance.stub(:save).and_return(false)
        post :create, {:proyectos_user => { "user_id" => "invalid value" }}, valid_session
        assigns(:proyectos_user).should be_a_new(ProyectosUser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectosUser.any_instance.stub(:save).and_return(false)
        post :create, {:proyectos_user => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested proyectos_user" do
        proyectos_user = ProyectosUser.create! valid_attributes
        # Assuming there are no other proyectos_users in the database, this
        # specifies that the ProyectosUser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProyectosUser.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => proyectos_user.to_param, :proyectos_user => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested proyectos_user as @proyectos_user" do
        proyectos_user = ProyectosUser.create! valid_attributes
        put :update, {:id => proyectos_user.to_param, :proyectos_user => valid_attributes}, valid_session
        assigns(:proyectos_user).should eq(proyectos_user)
      end

      it "redirects to the proyectos_user" do
        proyectos_user = ProyectosUser.create! valid_attributes
        put :update, {:id => proyectos_user.to_param, :proyectos_user => valid_attributes}, valid_session
        response.should redirect_to(proyectos_user)
      end
    end

    describe "with invalid params" do
      it "assigns the proyectos_user as @proyectos_user" do
        proyectos_user = ProyectosUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectosUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => proyectos_user.to_param, :proyectos_user => { "user_id" => "invalid value" }}, valid_session
        assigns(:proyectos_user).should eq(proyectos_user)
      end

      it "re-renders the 'edit' template" do
        proyectos_user = ProyectosUser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProyectosUser.any_instance.stub(:save).and_return(false)
        put :update, {:id => proyectos_user.to_param, :proyectos_user => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested proyectos_user" do
      proyectos_user = ProyectosUser.create! valid_attributes
      expect {
        delete :destroy, {:id => proyectos_user.to_param}, valid_session
      }.to change(ProyectosUser, :count).by(-1)
    end

    it "redirects to the proyectos_users list" do
      proyectos_user = ProyectosUser.create! valid_attributes
      delete :destroy, {:id => proyectos_user.to_param}, valid_session
      response.should redirect_to(proyectos_users_url)
    end
  end

end
